version: '3.8'

services:
    frontend:
        image: antoniopapa1991/frontend
        ports:
            -   '8080:80'
        depends_on:
            -   backend
    backend:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '8000:8000'
        volumes:
            - .:/app
        depends_on:
            -   db

    db:
        image: mysql:5.7.40
        environment:
            MYSQL_DATABASE: admin
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
            MYSQL_ROOT_PASSWORD: admin
        volumes:
            -   ./storage/dbdata:/var/lib/mysql
        ports:
            -   '33066:3306'
